# CMake generated Testfile for 
# Source directory: /home/hobbes/projects/cad-solution/dxf
# Build directory: /home/hobbes/projects/cad-solution/dxf
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Blocks_test "/home/hobbes/projects/cad-solution/dxf/Blocks_test")
set_tests_properties(Blocks_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Document_test "/home/hobbes/projects/cad-solution/dxf/Document_test")
set_tests_properties(Document_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(EntityFactory_test "/home/hobbes/projects/cad-solution/dxf/EntityFactory_test")
set_tests_properties(EntityFactory_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Entity_test "/home/hobbes/projects/cad-solution/dxf/Entity_test")
set_tests_properties(Entity_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Section_test "/home/hobbes/projects/cad-solution/dxf/Section_test")
set_tests_properties(Section_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Arc_test "/home/hobbes/projects/cad-solution/dxf/Arc_test")
set_tests_properties(Arc_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(AttDef_test "/home/hobbes/projects/cad-solution/dxf/AttDef_test")
set_tests_properties(AttDef_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Attrib_test "/home/hobbes/projects/cad-solution/dxf/Attrib_test")
set_tests_properties(Attrib_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Ellipse_test "/home/hobbes/projects/cad-solution/dxf/Ellipse_test")
set_tests_properties(Ellipse_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Entities_test "/home/hobbes/projects/cad-solution/dxf/Entities_test")
set_tests_properties(Entities_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Face3d_test "/home/hobbes/projects/cad-solution/dxf/Face3d_test")
set_tests_properties(Face3d_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Insert_test "/home/hobbes/projects/cad-solution/dxf/Insert_test")
set_tests_properties(Insert_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Line_test "/home/hobbes/projects/cad-solution/dxf/Line_test")
set_tests_properties(Line_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(MText_test "/home/hobbes/projects/cad-solution/dxf/MText_test")
set_tests_properties(MText_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Point_test "/home/hobbes/projects/cad-solution/dxf/Point_test")
set_tests_properties(Point_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Text_test "/home/hobbes/projects/cad-solution/dxf/Text_test")
set_tests_properties(Text_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Layer_test "/home/hobbes/projects/cad-solution/dxf/Layer_test")
set_tests_properties(Layer_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(File_test "/home/hobbes/projects/cad-solution/dxf/File_test")
set_tests_properties(File_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(TableEntry_test "/home/hobbes/projects/cad-solution/dxf/TableEntry_test")
set_tests_properties(TableEntry_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(TableFactory_test "/home/hobbes/projects/cad-solution/dxf/TableFactory_test")
set_tests_properties(TableFactory_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Table_test "/home/hobbes/projects/cad-solution/dxf/Table_test")
set_tests_properties(Table_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
add_test(Tables_test "/home/hobbes/projects/cad-solution/dxf/Tables_test")
set_tests_properties(Tables_test PROPERTIES  _BACKTRACE_TRIPLES "/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;56;add_test;/home/hobbes/projects/cad-solution/dxf/CMakeLists.txt;0;")
subdirs("_deps/pugixml-build")
subdirs("_deps/rapidjson-build")
